# Generated by Django 5.0.3 on 2024-05-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='page_count',
            field=models.IntegerField(default=0),
        ),
    ]
