# Generated by Django 5.0.3 on 2024-05-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_birthday_date_users_phone_numer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='patronymic',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Отчество'),
        ),
    ]
