# Generated by Django 5.0.3 on 2024-05-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_page_count'),
        ('users', '0005_basketitem_wishitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('user', 'book')},
        ),
    ]
