# Generated by Django 5.0.3 on 2024-04-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=124, null=True)),
                ('surname', models.CharField(blank=True, max_length=124, null=True)),
                ('last_name', models.CharField(blank=True, max_length=124, null=True)),
                ('birth_date', models.DateField()),
                ('biography', models.TextField()),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'unique_together': {('name', 'surname', 'last_name', 'birth_date')},
            },
        ),
    ]
